### ISSUE TITLE
can be support bottomnavigationbar selectable items?

### ISSUE THREAD

**Issue by pishguy** [Kodam-zz/NestedNavigatorTabs#1]
like with Instagram can be support selectable bottom navigation items?

**Comment by Kodam-zz** [comment]
I'm not sure what do you mean by selectable bottom navigation item, because the BottomNavigationItem has an activeIcon property which is supported by default. If it doesn't fit your needs, you can use the bottomBarBuilder to implement your custom logic/UI.

**Comment by pishguy** [comment]
@Kodam-zz 

in instagram when we drived into nested page, this map saved into stack, this could happen every page, for example in Home we goes to 3 nested page `Home -> folower profile ->click on folowers-> select another folower` next we click on `Explore` and we doing the same way` 

now when we click on `backSpace` button, instagram can back from nested pages and if this map finished, that goes to another tab and that do the same way

**Comment by Kodam-zz** [comment]
It is not supported currently although it can be done, but you have to implement it yourself. I can release a new version with the possibility to override the onWillPop function. Then you have to  check if the current navigation stack can pop and if not, you can switch to a different stack. With navigation observers it is possible to track the different stacks

**Comment by pishguy** [comment]
@Kodam-zz are you interested we doing that together ?

**Comment by Kodam-zz** [comment]
Sorry for the late answer. I implemented the requested behavior for one of my projects and I will release it this weekend. It is a hacky solution, but I couldn't find any better. It is also possible to track when the given page becomes active/inactive because of switching between tabs, but that part depends on the Provider lib so I might separate them

**Comment by Kodam-zz** [comment]
0.2.0 has been released to pub.dev. Please check the new readme for instructions and feel free to report any bugs.
